//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UBSFund.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UBSFund.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ErrorPanel_Cancel {
            get {
                return ResourceManager.GetString("ErrorPanel_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorPanel_Error {
            get {
                return ResourceManager.GetString("ErrorPanel_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Cannot add stock!.
        /// </summary>
        public static string FundView_AddErrorMessage {
            get {
                return ResourceManager.GetString("FundView_AddErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add stock.
        /// </summary>
        public static string FundView_AddStock {
            get {
                return ResourceManager.GetString("FundView_AddStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string FundView_All {
            get {
                return ResourceManager.GetString("FundView_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bond.
        /// </summary>
        public static string FundView_Bond {
            get {
                return ResourceManager.GetString("FundView_Bond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string FundView_Currency {
            get {
                return ResourceManager.GetString("FundView_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equity.
        /// </summary>
        public static string FundView_Equity {
            get {
                return ResourceManager.GetString("FundView_Equity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fund.
        /// </summary>
        public static string FundView_Fund {
            get {
                return ResourceManager.GetString("FundView_Fund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Value.
        /// </summary>
        public static string FundView_MarketValue {
            get {
                return ResourceManager.GetString("FundView_MarketValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string FundView_Price {
            get {
                return ResourceManager.GetString("FundView_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price*.
        /// </summary>
        public static string FundView_Price_Required {
            get {
                return ResourceManager.GetString("FundView_Price_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string FundView_Quantity {
            get {
                return ResourceManager.GetString("FundView_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity*.
        /// </summary>
        public static string FundView_Quantity_Required {
            get {
                return ResourceManager.GetString("FundView_Quantity_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Name.
        /// </summary>
        public static string FundView_StockName {
            get {
                return ResourceManager.GetString("FundView_StockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Type.
        /// </summary>
        public static string FundView_StockType {
            get {
                return ResourceManager.GetString("FundView_StockType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Weight.
        /// </summary>
        public static string FundView_StockWeight {
            get {
                return ResourceManager.GetString("FundView_StockWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fund.
        /// </summary>
        public static string FundView_Title {
            get {
                return ResourceManager.GetString("FundView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Cost.
        /// </summary>
        public static string FundView_TransactionCost {
            get {
                return ResourceManager.GetString("FundView_TransactionCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Market Value.
        /// </summary>
        public static string SummaryControl_TotalMarketValue {
            get {
                return ResourceManager.GetString("SummaryControl_TotalMarketValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Number.
        /// </summary>
        public static string SummaryControl_TotalNumber {
            get {
                return ResourceManager.GetString("SummaryControl_TotalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Stock Weight.
        /// </summary>
        public static string SummaryControl_TotalStockWeight {
            get {
                return ResourceManager.GetString("SummaryControl_TotalStockWeight", resourceCulture);
            }
        }
    }
}
